/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiInfoRouteImport } from './routes/api/info'
import { Route as ApiReadyRouteImport } from './routes/api/ready'
import { Route as ApiScanRouteImport } from './routes/api/scan'
import { Route as ApiScanHashRouteImport } from './routes/api/scan.hash'
import { Route as ApiScanHashesRouteImport } from './routes/api/scan.hashes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInfoRoute = ApiInfoRouteImport.update({
  id: '/api/info',
  path: '/api/info',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReadyRoute = ApiReadyRouteImport.update({
  id: '/api/ready',
  path: '/api/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScanRoute = ApiScanRouteImport.update({
  id: '/api/scan',
  path: '/api/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScanHashRoute = ApiScanHashRouteImport.update({
  id: '/hash',
  path: '/hash',
  getParentRoute: () => ApiScanRoute,
} as any)
const ApiScanHashesRoute = ApiScanHashesRouteImport.update({
  id: '/hashes',
  path: '/hashes',
  getParentRoute: () => ApiScanRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/api/info': typeof ApiInfoRoute
  '/api/ready': typeof ApiReadyRoute
  '/api/scan': typeof ApiScanRouteWithChildren
  '/api/scan/hash': typeof ApiScanHashRoute
  '/api/scan/hashes': typeof ApiScanHashesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/api/info': typeof ApiInfoRoute
  '/api/ready': typeof ApiReadyRoute
  '/api/scan': typeof ApiScanRouteWithChildren
  '/api/scan/hash': typeof ApiScanHashRoute
  '/api/scan/hashes': typeof ApiScanHashesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/api/info': typeof ApiInfoRoute
  '/api/ready': typeof ApiReadyRoute
  '/api/scan': typeof ApiScanRouteWithChildren
  '/api/scan/hash': typeof ApiScanHashRoute
  '/api/scan/hashes': typeof ApiScanHashesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/health'
    | '/api/info'
    | '/api/ready'
    | '/api/scan'
    | '/api/scan/hash'
    | '/api/scan/hashes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/health'
    | '/api/info'
    | '/api/ready'
    | '/api/scan'
    | '/api/scan/hash'
    | '/api/scan/hashes'
  id:
    | '__root__'
    | '/'
    | '/api/health'
    | '/api/info'
    | '/api/ready'
    | '/api/scan'
    | '/api/scan/hash'
    | '/api/scan/hashes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiInfoRoute: typeof ApiInfoRoute
  ApiReadyRoute: typeof ApiReadyRoute
  ApiScanRoute: typeof ApiScanRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/info': {
      id: '/api/info'
      path: '/api/info'
      fullPath: '/api/info'
      preLoaderRoute: typeof ApiInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ready': {
      id: '/api/ready'
      path: '/api/ready'
      fullPath: '/api/ready'
      preLoaderRoute: typeof ApiReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scan': {
      id: '/api/scan'
      path: '/api/scan'
      fullPath: '/api/scan'
      preLoaderRoute: typeof ApiScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scan/hash': {
      id: '/api/scan/hash'
      path: '/hash'
      fullPath: '/api/scan/hash'
      preLoaderRoute: typeof ApiScanHashRouteImport
      parentRoute: typeof ApiScanRoute
    }
    '/api/scan/hashes': {
      id: '/api/scan/hashes'
      path: '/hashes'
      fullPath: '/api/scan/hashes'
      preLoaderRoute: typeof ApiScanHashesRouteImport
      parentRoute: typeof ApiScanRoute
    }
  }
}

interface ApiScanRouteChildren {
  ApiScanHashRoute: typeof ApiScanHashRoute
  ApiScanHashesRoute: typeof ApiScanHashesRoute
}

const ApiScanRouteChildren: ApiScanRouteChildren = {
  ApiScanHashRoute: ApiScanHashRoute,
  ApiScanHashesRoute: ApiScanHashesRoute,
}

const ApiScanRouteWithChildren =
  ApiScanRoute._addFileChildren(ApiScanRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiInfoRoute: ApiInfoRoute,
  ApiReadyRoute: ApiReadyRoute,
  ApiScanRoute: ApiScanRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
